remote_theme: thelehhman/plainwhite-jekyll

plainwhite:
  name: Hector Espert
  tagline: Developer
  date_format: "%b %-d, %Y"

  social_links:
    twitter: thelehhman
    github: thelehhman
    linkedIn: in/thelehhman # format: locale/username
