remote_theme: thelehhman/plainwhite-jekyll

plainwhite:
  name: Hector Espert
  tagline: Developer
  date_format: "%b %-d, %Y"

  social_links:
    twitter: blackleg
    github: hectorespert
    linkedIn: in/hectorespert
