title: Hector Espert
email: hectorespertpardo@gmail.com
description: Linuxero, no limpio Windows.

remote_theme: samarsault/plainwhite-jekyll

plainwhite:
  name: Hector Espert
  tagline: Linuxero, no limpio Windows.
  date_format: "%b %-d, %Y"

  social_links:
    twitter: blackleg
    github: hectorespert
    linkedIn: in/hectorespert
